belajar_djangodb/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<Input>[\w-]+)/$', views.ragamPost),
]

belajar_djangodb/djangodb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^sosmed/', include('sosmed.urls', namespace='sosmed')),
    url(r'^classBased/', include('classBased.urls', namespace='classBased'))
]

belajar_djangodb/sosmed/urls.py
from django.conf.urls import url

from .import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<delete_id>[1-9]|[1-9][0-9]|[1-9][0-9][0-9])$', views.delete, name='delete'),
    url(r'^update/(?P<update_id>[1-9]|[1-9][0-9]|[1-9][0-9][0-9])$', views.update, name='update'),
]

belajar_djangodb/sosmed/models.py
from django.db import models

# Create your models here.

class sosmedModel(models.Model):
    nama_depan = models.CharField(max_length=100)
    nama_belakang = models.CharField(max_length=100)
    username = models.CharField(max_length=100)

    def __str__(self):
        return "{} {}".format(self.id, self.username)

belajar_djangodb/sosmed/forms.py
from django import forms

from .models import sosmedModel

class sosmedForm(forms.ModelForm):
    class Meta:
        model = sosmedModel
        fields = [
            'nama_depan',
            'nama_belakang',
            'username'
        ]

        widgets = {
            'nama_depan': forms.TextInput(
                attrs={
                    'class':'form-control'
                }
            ),

            'nama_belakang': forms.TextInput(
                attrs={
                    'class':'form-control'
                }
            ),

            'username':forms.TextInput(
                attrs={
                    'class':'form-control'
                }
            )
        }

belajar_djangodb/sosmed/views.py
from django.shortcuts import render, redirect

# Create your views here.

from .models import sosmedModel
from .forms import sosmedForm

def index(request):

    semua_akun = sosmedModel.objects.all()

    context = {
        'heading':'Selamat datang di app sosmed',
        'semua_akun': semua_akun
    }

    return render(request, 'sosmed/index.html', context)

def create(request):

    form_sosmed = sosmedForm(request.POST or None)

    if request.method == 'POST':
        if form_sosmed.is_valid():
            form_sosmed.save()
        
        return redirect('sosmed:index')

    context = {
        'heading':'Create User Sosmed',
        'form_sosmed':form_sosmed
    }

    return render(request, 'sosmed/create.html', context)

def delete(request, delete_id):
    sosmedModel.objects.filter(id=delete_id).delete()
    return redirect('sosmed:index')

def update(request, update_id):

    modelUpdate = sosmedModel.objects.get(id=update_id)

    data = {
        'nama_depan': modelUpdate.nama_depan,
        'nama_belakang': modelUpdate.nama_belakang,
        'username': modelUpdate.username,
    }

    form_update = sosmedForm(request.POST or None, initial=data, instance=modelUpdate)

    if request.method == 'POST':
        if form_update.is_valid():
            form_update.save()

        return redirect('sosmed:index')
    
    context = {
        'heading':'Create User Sosmed',
        'form_sosmed':form_update
    }

    return render(request, 'sosmed/create.html', context)

belajar_djangodb/sosmed/templates/sosmed/create.html
{% extends 'base.html' %}

{% block titles %}
    {{heading}}
{% endblock titles %}
    

{% block contents %}
    <h2>Create Sosmed User</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="form-group">
                {{form_sosmed.label}}
                {{form_sosmed}}
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </div>
    </form>

{% endblock contents %}
    

belajar_djangodb/sosmed/templates/sosmed/index.html
{% extends 'base.html' %}

{% block title %}
    {{heading}}
{% endblock title %}


{% block contents %}
<br>
<h2>SOSMED USER TABLES</h2>
<br>
<table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Nama Depan</th>
        <th scope="col">Nama Belakang</th>
        <th scope="col">Username</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
        
        {% for akun in semua_akun %}
                        
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{akun.nama_depan}}</td>
                <td>{{akun.nama_belakang}}</td>
                <td>{{akun.username}}</td>
                <td><a class="btn btn-warning" href="{% url 'sosmed:update' akun.id %}">Edit</a></td>
                <td><a class="btn btn-danger" href="{% url 'sosmed:delete' akun.id %}">Hapus</a></td>
            </tr>

        {% endfor %}
    </tbody>

  </table>
  <a class="btn btn-primary" href="{% url 'sosmed:create' %}">Create User</a>      

{% endblock contents %}
    