belajar_djangodb/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<Input>[\w-]+)/$', views.ragamPost),
]

belajar_djangodb/classBased/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from .import views

urlpatterns = [

    #Beberapa cara memanggil template halaman menggunakan ClassBasedView

    #cara pertama : memakai class View saja
    url(r'^$', views.IndexClass.as_view(), name='index'),

    #cara kedua : memakai class TemplateView yang di deklarasikan di view.py
    url(r'^index1$', views.IndexClass2.as_view(template_name='classBased/classBased1.html'), name='index1'),

    #cara ketiga : langsung pakai class TemplateView di urls.py (statis)
    url(r'^index2$', TemplateView.as_view(template_name='classBased/classBased2.html'), name='index2'),

    #cara keempat : mengambil context pada TemplateView (lihat di views.py)
    url(r'^indexContext$', views.IndexContext.as_view(), name='indexContext')
]

belajar_djangodb/djangodb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^sosmed/', include('sosmed.urls', namespace='sosmed')),
    url(r'^classBased/', include('classBased.urls', namespace='classBased'))
]

belajar_djangodb/classBased/models.py
from django.db import models

# Create your models here.

belajar_djangodb/classBased/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic.base import TemplateView

# Create your views here.

class IndexClass(View):
    
    template_name = 'classBased/classBased.html'
    context = {
        'heading':'Ini views dengan menggunakan ClasBased'
    }

    def get(self, request):
        return render(request, self.template_name, self.context)

    def post(self, request):
        self.context['heading'] = 'ini POST'
        return render(request, self.template_name, self.context)


class IndexClass2(TemplateView):
    pass

class IndexContext(TemplateView):
    template_name = 'classBased/indexContext.html'

    def get_context_data(self):
        context = {
            'heading':'CONTEXT',
            'content': 'INI ISI CONTENT'
        }

        return context

belajar_djangodb/classBased/templates/classBased/classBased.html
{% extends 'base.html' %}

{% block title %}
    {{heading}}
{% endblock title %}


{% block contents %}
    <form method='POST'>
        {% csrf_token %}
        <button type="submit">POST</button>
    </form>

    <ul>
        <li><a href="{% url 'classBased:index' %} ">Index</a></li>
        <li><a href="{% url 'classBased:index1' %} ">Index1</a></li>
        <li><a href="{% url 'classBased:index2' %} ">Index2</a></li>
    </ul>
{% endblock contents %}
    
    

belajar_djangodb/classBased/templates/classBased/classBased1.html
{% extends 'base.html' %}

{% block title %}
    <h1>TemplateView</h1>
{% endblock title %}


{% block contents %}
    <h2>Home</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut perspiciatis inventore ad, doloribus neque laboriosam iusto, esse, minima accusantium libero autem iure pariatur. Debitis dolorum quam fugit iste, dolores voluptas.</p>
{% endblock contents %}
    
    

belajar_djangodb/classBased/templates/classBased/classBased2.html
{% extends 'base.html' %}

{% block title %}
    <h1>TemplateView 2</h1>
{% endblock title %}


{% block contents %}
    <h2>Home 2</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut perspiciatis inventore ad, doloribus neque laboriosam iusto, esse, minima accusantium libero autem iure pariatur. Debitis dolorum quam fugit iste, dolores voluptas.</p>
{% endblock contents %}
    
    

belajar_djangodb/classBased/templates/classBased/indexContext.html
{% extends 'base.html' %}

{% block title %}
    {{heading}}
{% endblock title %}


{% block contents %}
    <h2>{{heading}}</h2>
    <p>{{content}}</p>
{% endblock contents %}
    
    