belajar_djangodb/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<Input>[\w-]+)/$', views.ragamPost),
]

belajar_djangodb/djangodb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^sosmed/', include('sosmed.urls', namespace='sosmed')),
    url(r'^classBased/', include('classBased.urls', namespace='classBased'))
]

belajar_djangodb/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>
        
        {% block title %}
            
        {% endblock title %}
            
    </title>
  </head>
  <body>
    <div class="container">
        
        {% block contents %}
            
        {% endblock contents %}
            
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

belajar_djangodb/templates/index.html
<html>
    <head>
        <title>HOME</title>
    </head>
    <body>
        <h1>Perhatikan Contoh dibawah ini</h1>
        <ul>
            <li>
                <a href="{% url 'blog:index' %}">Blog</a>
            </li>
            <li>
                <a href="/admin">Admin</a>
            </li>
            <li>
                <a href="{% url 'contact:index' %}">Contact Form</a>
            </li>
            <li>
                <a href="{% url 'sosmed:index' %}">Sosmed Crud</a>
            </li>
        </ul>
    </body>
</html>